# Generated by Django 2.2.4 on 2020-08-07 20:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_id', models.BigIntegerField()),
                ('channel_username', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=200, null=True)),
                ('bot_token', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_caption', models.TextField(blank=True, null=True)),
                ('image_caption_font', models.TextField(default='default', help_text='Available fonts: <code>arial</code>, <code>tannenbaum</code>, <code>dejavu_sans</code>, <code>dejavu_sans_mono</code>, <code>dejavu_serif_mono</code>, <code>lato_thin</code>, <code>lato_heavy</code>, <code>lato_italic</code>')),
                ('image_caption_direction', models.CharField(choices=[('n', 'North'), ('nw', 'North-west'), ('w', 'West'), ('sw', 'South-west'), ('s', 'South'), ('se', 'South-east'), ('e', 'East'), ('ne', 'North-east'), ('c', 'Center')], default='nw', max_length=2)),
                ('image_caption_alpha', models.IntegerField(default=100)),
                ('_reactions', models.TextField(blank=True, null=True)),
                ('zombie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.BigIntegerField()),
                ('bot_token', models.CharField(max_length=200)),
                ('_user_state', models.CharField(choices=[('idle', 'idle'), ('set caption menu', 'set caption menu'), ('set caption', 'set caption'), ('settings menu', 'settings menu'), ('channel settings menu', 'channel settings menu'), ('pre remove channel', 'pre remove channel'), ('set reactions menu', 'set reactions menu'), ('set reactions', 'set reactions'), ('set image caption menu', 'set image caption menu'), ('set image caption', 'set image caption'), ('set image caption next', 'set image caption next'), ('set forwarder menu', 'set forwarder menu'), ('set forwarder to', 'set forwarder to'), ('set image caption alpha', 'set image caption alpha')], default='idle', max_length=100, verbose_name='State')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('user_fullname', models.CharField(max_length=200)),
                ('zombie', models.BooleanField(default=False)),
                ('current_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_user', to='bot.ChannelSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reaction', models.CharField(max_length=100)),
                ('message', models.BigIntegerField()),
                ('bot_token', models.CharField(max_length=200)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.ChannelSettings')),
                ('users', models.ManyToManyField(blank=True, related_name='reactions', to='bot.UserSettings')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('media_group_id', models.BigIntegerField(null=True)),
                ('message_id', models.BigIntegerField()),
                ('edited', models.BooleanField(default=False)),
                ('bot_token', models.CharField(max_length=200)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media_groups', to='bot.ChannelSettings')),
            ],
        ),
        migrations.AddField(
            model_name='channelsettings',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.UserSettings'),
        ),
        migrations.AddField(
            model_name='channelsettings',
            name='forward_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forward_from', to='bot.ChannelSettings'),
        ),
        migrations.AddField(
            model_name='channelsettings',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='channels', to='bot.UserSettings'),
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('user_id', 'bot_token'), name='user_bot_unique'),
        ),
        migrations.AddConstraint(
            model_name='mediagroup',
            constraint=models.UniqueConstraint(fields=('media_group_id', 'bot_token'), name='mediagroup_bot_unique'),
        ),
        migrations.AddConstraint(
            model_name='channelsettings',
            constraint=models.UniqueConstraint(fields=('channel_id', 'bot_token'), name='channel_bot_unique'),
        ),
    ]
