# Generated by Django 2.2.1 on 2019-05-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='_user_state',
            field=models.CharField(choices=[('idle', 'idle'), ('set caption menu', 'set caption menu'), ('set caption', 'set caption'), ('settings menu', 'settings menu'), ('channel settings menu', 'channel settings menu'), ('pre remove channel', 'pre remove channel')], default='idle', max_length=100, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('channel_username', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=200, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.UserSettings')),
                ('users', models.ManyToManyField(blank=True, related_name='channels', to='bot.UserSettings')),
            ],
        ),
        migrations.AddField(
            model_name='usersettings',
            name='current_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_user', to='bot.ChannelSettings'),
        ),
    ]
