# Generated by Django 2.2.15 on 2020-08-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsettings',
            name='forward_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_from', to='bot.ChannelSettings'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.ChannelSettings'),
        ),
    ]
