# Generated by Django 2.2.15 on 2020-08-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200808_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediagroup',
            name='edited',
        ),
    ]
