# Generated by Django 2.2.4 on 2019-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190528_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='_user_state',
            field=models.CharField(choices=[('idle', 'idle'), ('set caption menu', 'set caption menu'), ('set caption', 'set caption'), ('settings menu', 'settings menu'), ('channel settings menu', 'channel settings menu'), ('pre remove channel', 'pre remove channel'), ('set reactions menu', 'set reactions menu'), ('set reactions', 'set reactions'), ('set image caption menu', 'set image caption menu'), ('set image caption', 'set image caption')], default='idle', max_length=100, verbose_name='State'),
        ),
    ]
