# Generated by Django 2.2.4 on 2019-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20190807_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='image_caption_font',
            field=models.TextField(default='default'),
        ),
    ]
