# Generated by Django 2.2.4 on 2019-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_channelsettings_image_caption_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsettings',
            name='image_caption_direction',
            field=models.CharField(choices=[('n', 'North'), ('nw', 'North-west'), ('w', 'West'), ('sw', 'South-west'), ('s', 'South'), ('se', 'South-east'), ('e', 'East'), ('ne', 'North-east'), ('c', 'Center')], default='nw', max_length=2),
        ),
    ]
