# Generated by Django 2.2.4 on 2020-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20190828_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsettings',
            name='image_caption_font',
            field=models.TextField(default='default', help_text='Available fonts: <code>arial</code>, <code>tannenbaum</code>, <code>dejavu_sans</code>, <code>dejavu_sans_mono</code>, <code>dejavu_serif_mono</code>, <code>lato_thin</code>, <code>lato_heavy</code>, <code>lato_italic</code>'),
        ),
    ]
