# Generated by Django 2.2.4 on 2020-02-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20200209_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='zombie',
            field=models.BooleanField(default=False),
        ),
    ]
