# Generated by Django 2.2.4 on 2020-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_channelsettings_zombie'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='zombie',
            field=models.BooleanField(default=False),
        ),
    ]
