# Generated by Django 2.2.4 on 2020-05-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_usersettings_zombie'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsettings',
            name='forward_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forward_from', to='bot.ChannelSettings'),
        ),
    ]
